# Generated by Django 4.2.30 on 2026-06-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, default=0, null=True)),
                ('sma_4', models.FloatField(blank=True, null=True)),
                ('sma_9', models.FloatField(blank=True, null=True)),
                ('sma_50', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_price',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
