# Generated by Django 4.2.30 on 2026-06-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'managed': False, 'ordering': ['-date']},
        ),
    ]
