# Generated by Django 4.2.30 on 2026-06-16 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=4, max_digits=12)),
                ('profit_loss_percent', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buy_date', models.DateField()),
                ('sell_date', models.DateField()),
                ('holding_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_investments', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'closed_investments',
                'ordering': ['-sell_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BUY_DEBIT', 'Buy Debit'), ('SELL_CREDIT', 'Sell Credit'), ('DIVIDEND', 'Dividend')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_account',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cash_balance', models.DecimalField(decimal_places=4, max_digits=14)),
                ('invested_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_profit_loss', models.DecimalField(decimal_places=4, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_snapshot',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holdings',
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
